export default {
  id: 'cp:otoroshi.next.plugins.NgHasAllowedUsersValidator',
  config_schema: {
    usernames: {
      type: 'array',
      array: true,
      format: null,
      label: 'usernames',
    },
    emails: {
      type: 'array',
      array: true,
      format: null,
      label: 'email addresses',
    },
    email_domains: {
      type: 'array',
      array: true,
      format: null,
      label: 'email domains',
    },
    metadata_match: {
      type: 'array',
      array: true,
      format: null,
      label: 'otoroshi data match (IAM metadata)',
    },
    metadata_not_match: {
      type: 'array',
      array: true,
      format: null,
      label: 'otoroshi data not match (IAM metadata)',
    },
    otoroshi_data_match: {
      type: 'array',
      array: true,
      format: null,
      label: 'metadata match (auth. config metadata, etc)',
    },
    otoroshi_data_not_match: {
      type: 'array',
      array: true,
      format: null,
      label: 'metadata not match (auth. config metadata, etc)',
    },
    profile_match: {
      type: 'array',
      array: true,
      format: null,
      label: 'profile match',
    },
    profile_not_match: {
      type: 'array',
      array: true,
      format: null,
      label: 'profile not match',
    },
  },
  config_flow: [
    'usernames',
    'emails',
    'email_domains',
    'metadata_match',
    'metadata_not_match',
    'otoroshi_data_match',
    'otoroshi_data_not_match',
    'profile_match',
    'profile_not_match',
  ],
};
