FROM openjdk:11

ENV HOME=/root

WORKDIR $HOME

RUN mkdir -p /root/otoroshi
RUN mkdir -p /root/coder

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -y
RUN apt-get install -y git \
    wget \
    curl \
    vim \
    ack \
    tig \
    tree \
    apt-transport-https \
    openssl \
    build-essential \
    yarn
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.1/install.sh | bash
RUN wget --quiet https://github.com/sbt/sbt/releases/download/v1.3.3/sbt-1.3.3.zip
RUN unzip $HOME/sbt-1.3.3.zip
RUN rm -f $HOME/sbt-1.3.3.zip
RUN chmod -R 777 $HOME/.nvm

RUN export NVM_DIR="/root/.nvm" && . "/root/.nvm/nvm.sh"
RUN echo "export PATH=$PATH:/root/sbt/bin" >> .bashrc
RUN echo "export NVM_DIR=\"/root/.nvm\"" >> .bashrc
RUN echo ". \"/root/.nvm/nvm.sh\"" >> .bashrc

RUN echo "Installing node"
RUN export NVM_DIR="/root/.nvm" && \
    . "/root/.nvm/nvm.sh" && \
    nvm install 18 && \
    nvm use 18 && \
    nvm alias default 18
