addSbtPlugin("org.playframework" % "sbt-plugin"   % "3.0.8")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.5.4")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"  % "0.6.3")
addSbtPlugin("io.spray"          % "sbt-revolver" % "0.10.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.12.2")
addSbtPlugin("ch.epfl.scala"     % "sbt-bloop"    % "2.0.10")
addDependencyTreePlugin
addSbtPlugin("com.github.sbt" % "sbt-pgp"        % "2.3.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.11.0")
// addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")
//addSbtPlugin("ch.epfl.scala" % "sbt-scala3-migrate" % "0.7.2")
//addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.11.1")
