# Mise file (https://mise.jdx.dev/) for otoroshi
#
# prepare: mise install
# install all js deps: mise run install-js-deps
# dev: mise run dev
# build jar: mise run build
# run jar: mise run 
# run dev doc server: mise run dev-doc 
# build doc website: mise run build-doc

[tools]
java = "openjdk-17.0.2"
sbt = "1.7.2"
node = "20"

[tasks.install-frontend-js-deps]
description = "Install frontend dependencies"
dir = "otoroshi/javascript"
run = "npm install"

[tasks.install-doc-js-deps]
description = "Install documentation dependencies"
dir = "manual/next"
run = "npm install"

[tasks.install-js-deps]
description = "Install js dependencies"
run = [
  { task = "install-frontend-js-deps" },
  { task = "install-doc-js-deps"}
]

[tasks.dev-doc]
description = "Run documentation dev server"
dir = "manual/next"
run = "npm run start"

[tasks.build-doc]
description = "Build the documentation site"
dir = "manual/next"
run = "npm run build"

[tasks.dev-backend]
description = "Run otoroshi in dev mode with sbt"
dir = "otoroshi"
run = "sbt --java-home $JAVA_HOME ~reStart"

[tasks.dev-backend.env]
#OTOROSHI_INITIAL_ADMIN_LOGIN = "admin@otoroshi.io"
#OTOROSHI_INITIAL_ADMIN_PASSWORD = "password"
#OTOROSHI_API_CLIENT_ID = "admin"
#OTOROSHI_API_CLIENT_SECRET = "secret"

[tasks.dev-frontend]
description = "Start frontend dev server"
dir = "otoroshi/javascript"
run = "npm run webpack:start"

[tasks.dev]
description = "Start otoroshi backend + frontend in dev mode"
dir = "otoroshi"
depends = ["dev-backend", "dev-frontend"]
run = "true"

[tasks.build-backend]
description = "Build otoroshi backend (compile , assembly)"
dir = "otoroshi"
run = "sbt --java-home $JAVA_HOME clean compile assembly"

[tasks.build-frontend]
description = "Build otoroshi frontend"
dir = "otoroshi/javascript"
run = "npm run webpack:build"

[tasks.build]
description = "Build otoroshi (backend + frontend)"
run = [
  { task = "build-frontend" },
  { task = "build-backend" }
]

[tasks.jar]
description = "Run otoroshi locally"
dir = "otoroshi"
run = "$JAVA_HOME/bin/java -jar target/scala-2.12/otoroshi.jar"

[tasks.jar.env]
PORT = "8080"
OTOROSHI_STORAGE = "file"
OTOROSHI_ENV = "prod"
OTOROSHI_INITIAL_ADMIN_LOGIN = "admin@otoroshi.io"
OTOROSHI_INITIAL_ADMIN_PASSWORD = "password"
OTOROSHI_API_CLIENT_ID = "admin"
OTOROSHI_API_CLIENT_SECRET = "secret"
OTOROSHI_DOMAIN = "oto.tools" # default oto.tools, resolves to 127.0.0.1
