---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otoroshi-leader-deployment
spec:
  selector:
    matchLabels:
      run: otoroshi-leader-deployment
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        run: otoroshi-leader-deployment
    spec:
      serviceAccountName: otoroshi-admin-user
      terminationGracePeriodSeconds: 60
      hostNetwork: false
      restartPolicy: Always
      containers:
      - image: maif/otoroshi:17.16.0-dev-jdk11
        imagePullPolicy: IfNotPresent
        name: otoroshi-leader
        ports:
          - containerPort: 8080
            name: "http"
            protocol: TCP
          - containerPort: 8443
            name: "https"
            protocol: TCP
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_STORAGE_ROOT
            value: otoroshi
          - name: APP_STORAGE
            value: lettuce
          - name: CLUSTER_MODE
            value: Leader
          - name: CLUSTER_AUTO_UPDATE_STATE
            value: 'true'
          - name: CLUSTER_MTLS_ENABLED
            value: 'true'
          - name: CLUSTER_MTLS_LOOSE
            value: 'true'
          - name: CLUSTER_MTLS_TRUST_ALL
            value: 'true'
          - name: HEALTH_LIMIT
            value: "5000"
          - name: SSL_OUTSIDE_CLIENT_AUTH
            value: Want
          - name: HTTPS_WANT_CLIENT_AUTH
            value: "true"
          - name: JAVA_OPTS
            value: '-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0'
          - name: APP_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: otoroshi-config
                key: domain
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: otoroshi-redis-secret
                key: redisUrl
          - name: OTOROSHI_INITIAL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: password
          - name: ADMIN_API_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: clientId
          - name: CLUSTER_LEADER_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: clientId
          - name: ADMIN_API_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: clientSecret
          - name: CLUSTER_LEADER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: clientSecret
          - name: OTOROSHI_SECRET
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: otoroshiSecret
          - name: CLUSTER_LEADER_URL
            value: https://otoroshi-leader-api-service.$(POD_NAMESPACE).svc.cluster.local:8443
          - name: CLUSTER_LEADER_HOST
            value: otoroshi-leader-api-service.$(POD_NAMESPACE).svc.cluster.local
          - name: ADMIN_API_ADDITIONAL_EXPOSED_DOMAIN
            value: otoroshi-leader-api-service.$(POD_NAMESPACE).svc.cluster.local
          - name: OTOROSHI_INITIAL_CUSTOMIZATION
            value: file:///etc/otoroshi/initial-customization.json
        volumeMounts:
          - name: initial-customization
            mountPath: /etc/otoroshi
            readOnly: true
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
      volumes:
        - name: initial-customization
          configMap:
            name: otoroshi-initial-customization
            items:
              - key: initial-customization.json
                path: initial-customization.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otoroshi-worker-deployment
spec:
  selector:
    matchLabels:
      run: otoroshi-worker-deployment
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        run: otoroshi-worker-deployment
    spec:
      serviceAccountName: otoroshi-admin-user
      terminationGracePeriodSeconds: 60
      hostNetwork: false
      restartPolicy: Always
      containers:
      - image: maif/otoroshi:17.16.0-dev-jdk11
        imagePullPolicy: IfNotPresent
        name: otoroshi-worker
        ports:
          - containerPort: 8080
            name: "http"
            protocol: TCP
          - containerPort: 8443
            name: "https"
            protocol: TCP
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_STORAGE_ROOT
            value: otoroshi
          - name: CLUSTER_MODE
            value: Worker
          - name: CLUSTER_AUTO_UPDATE_STATE
            value: 'true'
          - name: CLUSTER_MTLS_ENABLED
            value: 'true'
          - name: CLUSTER_MTLS_LOOSE
            value: 'true'
          - name: CLUSTER_MTLS_TRUST_ALL
            value: 'true'
          - name: HEALTH_LIMIT
            value: "5000"
          - name: SSL_OUTSIDE_CLIENT_AUTH
            value: Want
          - name: HTTPS_WANT_CLIENT_AUTH
            value: "true"
          - name: JAVA_OPTS
            value: '-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0'
          - name: APP_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: otoroshi-config
                key: domain
          - name: OTOROSHI_INITIAL_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: password
          - name: ADMIN_API_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: clientId
          - name: CLUSTER_LEADER_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: clientId
          - name: ADMIN_API_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: clientSecret
          - name: CLUSTER_LEADER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: clientSecret
          - name: OTOROSHI_SECRET
            valueFrom:
              secretKeyRef:
                name: otoroshi-admin-secret
                key: otoroshiSecret
          - name: CLUSTER_LEADER_URL
            value: https://otoroshi-leader-api-service.$(POD_NAMESPACE).svc.cluster.local:8443
          - name: CLUSTER_LEADER_HOST
            value: otoroshi-leader-api-service.$(POD_NAMESPACE).svc.cluster.local
          - name: ADMIN_API_ADDITIONAL_EXPOSED_DOMAIN
            value: otoroshi-leader-api-service.$(POD_NAMESPACE).svc.cluster.local
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: otoroshi-leader-api-service
spec:
  selector:
    run: otoroshi-leader-deployment
  ports:
  - port: 8080
    name: "http"
    targetPort: "http"
  - port: 8443
    name: "https"
    targetPort: "https"
---
apiVersion: v1
kind: Service
metadata:
  name: otoroshi-leader-service
spec:
  selector:
    run: otoroshi-leader-deployment
  ports:
  - port: 8080
    name: "http"
    targetPort: "http"
  - port: 8443
    name: "https"
    targetPort: "https"
---
apiVersion: v1
kind: Service
metadata:
  name: otoroshi-worker-service
spec:
  selector:
    run: otoroshi-worker-deployment
  ports:
  - port: 8080
    name: "http"
    targetPort: "http"
  - port: 8443
    name: "https"
    targetPort: "https"
---
apiVersion: v1
kind: Service
metadata:
  name: otoroshi-leader-external-service
spec:
  type: LoadBalancer
  selector:
    run: otoroshi-leader-deployment
  ports:
  - port: 80
    name: "http"
    targetPort: "http"
  - port: 443
    name: "https"
    targetPort: "https"
---
apiVersion: v1
kind: Service
metadata:
  name: otoroshi-worker-external-service
spec:
  type: LoadBalancer
  selector:
    run: otoroshi-worker-deployment
  ports:
  - port: 80
    name: "http"
    targetPort: "http"
  - port: 443
    name: "https"
    targetPort: "https"
---
apiVersion: proxy.otoroshi.io/v1
kind: Certificate
metadata:
  name: otoroshi-service-certificate
spec:
  description: certificate for otoroshi-service
  autoRenew: true
  csr:
    issuer: CN=Otoroshi Root
    hosts:
      - otoroshi-service
      - otoroshi-service.otoroshi.svc.cluster.local
      - otoroshi-api-service.otoroshi.svc.cluster.local
      - otoroshi.oto.tools
      - otoroshi-api.oto.tools
      - privateapps.oto.tools
    key:
      algo: rsa
      size: 2048
    subject: uid=otoroshi-service-cert, O=Otoroshi
    client: false
    ca: false
    duration: 31536000000
    signatureAlg: SHA256WithRSAEncryption
    digestAlg: SHA-256
