// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Overview',
    },
    'about',
    'architecture',
    'features',
    'getting-started',
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'doc',
        id: 'install/index',
      },
      items: [
        'install/get-otoroshi',
        'install/setup-otoroshi',
        'install/run-otoroshi',
      ],
    },
    {
      type: 'category',
      label: 'Main Entities',
      link: {
        type: 'doc',
        id: 'entities/index',
      },
      items: [
        'entities/routes',
        'entities/apis',
        'entities/backends',
        'entities/apikeys',
        'entities/organizations',
        'entities/teams',
        'entities/service-groups',
        'entities/jwt-verifiers',
        'entities/global-config',
        'entities/tcp-services',
        'entities/auth-modules',
        'entities/certificates',
        'entities/data-exporters',
        'entities/service-descriptors',
        'entities/remote-catalogs',
        'entities/http-listeners',
        'entities/workflows',
        'entities/wasm-plugins',
        'entities/route-templates',
        'entities/error-templates',
        'entities/otoroshi-admins',
      ],
    },
    {
      type: 'category',
      label: 'Detailed Topics',
      link: {
        type: 'doc',
        id: 'topics/index',
      },
      items: [
        'topics/engine',
        'topics/expression-language',
        'topics/secrets',
        'topics/otoroshi-protocol',
        'topics/tls',
        'topics/user-rights',
        'topics/events-and-analytics',
        'topics/monitoring',
        'topics/sessions-mgmt',
        'topics/wasm-usage',
        'topics/chaos-engineering',
        'topics/pki',
        'topics/dev-portal',
        'topics/graphql-composer',
        'topics/tunnels',
        'topics/relay-routing',
        'topics/netty-server',
        'topics/http3',
        'topics/opentelemetry',
        'topics/green-score',
        'topics/http-listeners',
        'topics/circuit-breaker',
        'topics/durations',
        'topics/workflows',
        'topics/workflows-editor',
        'topics/remote-catalogs',
        'topics/kubernetes-gateway-api',
        'topics/admin-extensions',
        'topics/otoroshictl',
        'topics/ai-gateway',
        'topics/deprecating-sd',
        'topics/anonymous-reporting',
      ],
    },
    {
      type: 'category',
      label: 'Quick Tutorials',
      link: {
        type: 'doc',
        id: 'quick-tutorials/index',
      },
      items: [
        'quick-tutorials/one-header-to-rule-them-all',
        'quick-tutorials/stop-sharing-secrets-use-asymmetric-signatures',
      ],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      link: {
        type: 'doc',
        id: 'how-to-s/index',
      },
      items: [
        'how-to-s/create-your-first-api',
        'how-to-s/secure-with-apikey',
        'how-to-s/secure-an-app-with-jwt-verifiers',
        'how-to-s/secure-app-with-auth0',
        'how-to-s/secure-app-with-keycloak',
        'how-to-s/secure-app-with-ldap',
        'how-to-s/secure-with-oauth1-client',
        'how-to-s/secure-with-oauth2-client-credentials',
        'how-to-s/create-custom-auth-module',
        'how-to-s/secure-the-communication-between-a-backend-app-and-otoroshi',
        'how-to-s/end-to-end-mtls',
        'how-to-s/tls-using-lets-encrypt',
        'how-to-s/tls-termination-using-own-certificates',
        'how-to-s/export-events-to-elastic',
        'how-to-s/export-alerts-using-mailgun',
        'how-to-s/communicate-with-kafka',
        'how-to-s/import-export-otoroshi-datastore',
        'how-to-s/setup-otoroshi-cluster',
        'how-to-s/working-with-eureka',
        'how-to-s/tailscale-integration',
        'how-to-s/wasm-usage',
        'how-to-s/wasmo-installation',
        'how-to-s/instantiate-waf-coraza',
        'how-to-s/zip-backend-plugin',
        'how-to-s/calling-otoroshi-from-a-frontend',
        'how-to-s/resources-loader',
        'how-to-s/custom-log-levels',
        'how-to-s/custom-initial-state',
        'how-to-s/setup-ai-gateway-with-otoroshictl',
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {
        type: 'doc',
        id: 'plugins/index',
      },
      items: [
        'plugins/plugins-system',
        'plugins/create-plugins',
        'plugins/built-in-plugins',
      ],
    },
    {
      type: 'category',
      label: 'Deploy to Production',
      link: {
        type: 'doc',
        id: 'deploy/index',
      },
      items: [
        'deploy/kubernetes',
        'deploy/clustering',
        'deploy/scaling',
        'deploy/aws',
        'deploy/clever-cloud',
      ],
    },
    'api',
    'dev',
  ],
};

export default sidebars;
