apiVersion: v1
entries:
  otoroshi:
  - apiVersion: v3
    appVersion: 17.15.1
    created: "2026-04-22T20:53:17.263141668Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 21.2.9
    description: An Otoroshi based Kubernetes ingress controller
    digest: 1fbe732eb945e6f145c19829ab3c6726814a27c918b752e979e0a5e5b0e7dda8
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-17.15.1.tgz
    version: 17.15.1
  - apiVersion: v3
    appVersion: 17.15.0
    created: "2026-04-22T20:53:17.256310695Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 21.2.9
    description: An Otoroshi based Kubernetes ingress controller
    digest: c85a373de2aa4683b90e5d2d7d1385ebfc64855e6501f71a5faaecac9354db92
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-17.15.0.tgz
    version: 17.15.0
  - apiVersion: v3
    appVersion: 1.5.10
    created: "2026-04-22T20:53:17.217068551Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 35b1af9a88bb1cff21f66a41de811d20029bb2a1bf7c5d9563ec322d7082b44c
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.10.tgz
    version: 1.5.10
  - apiVersion: v3
    appVersion: 1.5.9
    created: "2026-04-22T20:53:17.249466148Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: e4de530f2e3240f829fc75db7cf3b504ef60c2b5f5bf9bb5800104a565b6ab0d
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.9.tgz
    version: 1.5.9
  - apiVersion: v3
    appVersion: 1.5.8
    created: "2026-04-22T20:53:17.24475535Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 4838df2991ad5d9bba925716cf40d4cfe72160b4f7ae0a63bb6ea380158d5031
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.8.tgz
    version: 1.5.8
  - apiVersion: v3
    appVersion: 1.5.6
    created: "2026-04-22T20:53:17.239717145Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: c5b924b33bc998672224700adbeb22dec95b06054112d2d598c00bb5f06e4564
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.6.tgz
    version: 1.5.6
  - apiVersion: v3
    appVersion: 1.5.5
    created: "2026-04-22T20:53:17.235630628Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: ef9e4325b6ab55e99b003d97664f16091811135f63b4a872e3a4a1f4615dd4e0
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.5.tgz
    version: 1.5.5
  - apiVersion: v3
    appVersion: 1.5.4
    created: "2026-04-22T20:53:17.230665885Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 71c90ff63614c5bd95bbabba4a0f3077a8d730ba82643aaf136aeac96c2812ab
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.4.tgz
    version: 1.5.4
  - apiVersion: v3
    appVersion: 1.5.3
    created: "2026-04-22T20:53:17.226137634Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 560fbc62853ebcbdea1474013d5c3ea0d9c62a61964265295311d1f15bc5f717
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.3.tgz
    version: 1.5.3
  - apiVersion: v3
    appVersion: 1.5.2
    created: "2026-04-22T20:53:17.221685753Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 33be8d43ec7cc787a2bbab634805ba3ff0e83bd2c35a527d3ea0cf368b9d2330
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.2.tgz
    version: 1.5.2
  - apiVersion: v3
    appVersion: 1.5.1
    created: "2026-04-22T20:53:17.212484796Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 271325c8151da7ec906e6ea51eec9390f84d85b79d78fd931d6d8ecc2e4df2dd
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.1.tgz
    version: 1.5.1
  - apiVersion: v3
    appVersion: 1.5.0
    created: "2026-04-22T20:53:17.208458261Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: e0bffdbb468e094b1c7ef92ab984b734d93d0e4d6d2881ceb5065259d5d3ad0e
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v3
    appVersion: 1.5.0-rc.4
    created: "2026-04-22T20:53:17.203384938Z"
    dependencies:
    - condition: global.prod
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 15.0.0
    description: An Otoroshi based Kubernetes ingress controller
    digest: 4bc7a10682d1c014fb0507af24817a7bb95775a728d6243d55beecc249f78c40
    icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
    keywords:
    - otoroshi
    - ingress
    - reverseproxy
    - apimanager
    maintainers:
    - name: mathieuancelin
    name: otoroshi
    sources:
    - https://github.com/MAIF/otoroshi
    type: application
    urls:
    - https://maif.github.io/otoroshi/helm/otoroshi-1.5.0-rc.4.tgz
    version: 1.5.0-rc.4
generated: "2026-04-22T20:53:17.19832013Z"
