// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reflection.proto

package otoroshi.next.plugins.grpc;

public interface ExtensionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1alpha.ExtensionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Fully-qualified type name. The format should be &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string containing_type = 1;</code>
   * @return The containingType.
   */
  java.lang.String getContainingType();
  /**
   * <pre>
   * Fully-qualified type name. The format should be &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string containing_type = 1;</code>
   * @return The bytes for containingType.
   */
  com.google.protobuf.ByteString
      getContainingTypeBytes();

  /**
   * <code>int32 extension_number = 2;</code>
   * @return The extensionNumber.
   */
  int getExtensionNumber();
}
