// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reflection.proto

package otoroshi.next.plugins.grpc;

public interface ListServiceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.reflection.v1alpha.ListServiceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  java.util.List<otoroshi.next.plugins.grpc.ServiceResponse> 
      getServiceList();
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  otoroshi.next.plugins.grpc.ServiceResponse getService(int index);
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  int getServiceCount();
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  java.util.List<? extends otoroshi.next.plugins.grpc.ServiceResponseOrBuilder> 
      getServiceOrBuilderList();
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  otoroshi.next.plugins.grpc.ServiceResponseOrBuilder getServiceOrBuilder(
      int index);
}
