// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reflection.proto

package otoroshi.next.plugins.grpc;

/**
 * <pre>
 * A list of ServiceResponse sent by the server answering list_services request.
 * </pre>
 *
 * Protobuf type {@code grpc.reflection.v1alpha.ListServiceResponse}
 */
public final class ListServiceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.ListServiceResponse)
    ListServiceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListServiceResponse.newBuilder() to construct.
  private ListServiceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListServiceResponse() {
    service_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListServiceResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ListServiceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ListServiceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            otoroshi.next.plugins.grpc.ListServiceResponse.class, otoroshi.next.plugins.grpc.ListServiceResponse.Builder.class);
  }

  public static final int SERVICE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<otoroshi.next.plugins.grpc.ServiceResponse> service_;
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public java.util.List<otoroshi.next.plugins.grpc.ServiceResponse> getServiceList() {
    return service_;
  }
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends otoroshi.next.plugins.grpc.ServiceResponseOrBuilder> 
      getServiceOrBuilderList() {
    return service_;
  }
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public int getServiceCount() {
    return service_.size();
  }
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ServiceResponse getService(int index) {
    return service_.get(index);
  }
  /**
   * <pre>
   * The information of each service may be expanded in the future, so we use
   * ServiceResponse message to encapsulate it.
   * </pre>
   *
   * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ServiceResponseOrBuilder getServiceOrBuilder(
      int index) {
    return service_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < service_.size(); i++) {
      output.writeMessage(1, service_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < service_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, service_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof otoroshi.next.plugins.grpc.ListServiceResponse)) {
      return super.equals(obj);
    }
    otoroshi.next.plugins.grpc.ListServiceResponse other = (otoroshi.next.plugins.grpc.ListServiceResponse) obj;

    if (!getServiceList()
        .equals(other.getServiceList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getServiceCount() > 0) {
      hash = (37 * hash) + SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getServiceList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ListServiceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(otoroshi.next.plugins.grpc.ListServiceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A list of ServiceResponse sent by the server answering list_services request.
   * </pre>
   *
   * Protobuf type {@code grpc.reflection.v1alpha.ListServiceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.ListServiceResponse)
      otoroshi.next.plugins.grpc.ListServiceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ListServiceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ListServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              otoroshi.next.plugins.grpc.ListServiceResponse.class, otoroshi.next.plugins.grpc.ListServiceResponse.Builder.class);
    }

    // Construct using otoroshi.next.plugins.grpc.ListServiceResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (serviceBuilder_ == null) {
        service_ = java.util.Collections.emptyList();
      } else {
        service_ = null;
        serviceBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ListServiceResponse_descriptor;
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ListServiceResponse getDefaultInstanceForType() {
      return otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ListServiceResponse build() {
      otoroshi.next.plugins.grpc.ListServiceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ListServiceResponse buildPartial() {
      otoroshi.next.plugins.grpc.ListServiceResponse result = new otoroshi.next.plugins.grpc.ListServiceResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(otoroshi.next.plugins.grpc.ListServiceResponse result) {
      if (serviceBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          service_ = java.util.Collections.unmodifiableList(service_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.service_ = service_;
      } else {
        result.service_ = serviceBuilder_.build();
      }
    }

    private void buildPartial0(otoroshi.next.plugins.grpc.ListServiceResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof otoroshi.next.plugins.grpc.ListServiceResponse) {
        return mergeFrom((otoroshi.next.plugins.grpc.ListServiceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(otoroshi.next.plugins.grpc.ListServiceResponse other) {
      if (other == otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance()) return this;
      if (serviceBuilder_ == null) {
        if (!other.service_.isEmpty()) {
          if (service_.isEmpty()) {
            service_ = other.service_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServiceIsMutable();
            service_.addAll(other.service_);
          }
          onChanged();
        }
      } else {
        if (!other.service_.isEmpty()) {
          if (serviceBuilder_.isEmpty()) {
            serviceBuilder_.dispose();
            serviceBuilder_ = null;
            service_ = other.service_;
            bitField0_ = (bitField0_ & ~0x00000001);
            serviceBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getServiceFieldBuilder() : null;
          } else {
            serviceBuilder_.addAllMessages(other.service_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              otoroshi.next.plugins.grpc.ServiceResponse m =
                  input.readMessage(
                      otoroshi.next.plugins.grpc.ServiceResponse.parser(),
                      extensionRegistry);
              if (serviceBuilder_ == null) {
                ensureServiceIsMutable();
                service_.add(m);
              } else {
                serviceBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<otoroshi.next.plugins.grpc.ServiceResponse> service_ =
      java.util.Collections.emptyList();
    private void ensureServiceIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        service_ = new java.util.ArrayList<otoroshi.next.plugins.grpc.ServiceResponse>(service_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        otoroshi.next.plugins.grpc.ServiceResponse, otoroshi.next.plugins.grpc.ServiceResponse.Builder, otoroshi.next.plugins.grpc.ServiceResponseOrBuilder> serviceBuilder_;

    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public java.util.List<otoroshi.next.plugins.grpc.ServiceResponse> getServiceList() {
      if (serviceBuilder_ == null) {
        return java.util.Collections.unmodifiableList(service_);
      } else {
        return serviceBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public int getServiceCount() {
      if (serviceBuilder_ == null) {
        return service_.size();
      } else {
        return serviceBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public otoroshi.next.plugins.grpc.ServiceResponse getService(int index) {
      if (serviceBuilder_ == null) {
        return service_.get(index);
      } else {
        return serviceBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder setService(
        int index, otoroshi.next.plugins.grpc.ServiceResponse value) {
      if (serviceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceIsMutable();
        service_.set(index, value);
        onChanged();
      } else {
        serviceBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder setService(
        int index, otoroshi.next.plugins.grpc.ServiceResponse.Builder builderForValue) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        service_.set(index, builderForValue.build());
        onChanged();
      } else {
        serviceBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder addService(otoroshi.next.plugins.grpc.ServiceResponse value) {
      if (serviceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceIsMutable();
        service_.add(value);
        onChanged();
      } else {
        serviceBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder addService(
        int index, otoroshi.next.plugins.grpc.ServiceResponse value) {
      if (serviceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureServiceIsMutable();
        service_.add(index, value);
        onChanged();
      } else {
        serviceBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder addService(
        otoroshi.next.plugins.grpc.ServiceResponse.Builder builderForValue) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        service_.add(builderForValue.build());
        onChanged();
      } else {
        serviceBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder addService(
        int index, otoroshi.next.plugins.grpc.ServiceResponse.Builder builderForValue) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        service_.add(index, builderForValue.build());
        onChanged();
      } else {
        serviceBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder addAllService(
        java.lang.Iterable<? extends otoroshi.next.plugins.grpc.ServiceResponse> values) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, service_);
        onChanged();
      } else {
        serviceBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder clearService() {
      if (serviceBuilder_ == null) {
        service_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        serviceBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public Builder removeService(int index) {
      if (serviceBuilder_ == null) {
        ensureServiceIsMutable();
        service_.remove(index);
        onChanged();
      } else {
        serviceBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public otoroshi.next.plugins.grpc.ServiceResponse.Builder getServiceBuilder(
        int index) {
      return getServiceFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public otoroshi.next.plugins.grpc.ServiceResponseOrBuilder getServiceOrBuilder(
        int index) {
      if (serviceBuilder_ == null) {
        return service_.get(index);  } else {
        return serviceBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public java.util.List<? extends otoroshi.next.plugins.grpc.ServiceResponseOrBuilder> 
         getServiceOrBuilderList() {
      if (serviceBuilder_ != null) {
        return serviceBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(service_);
      }
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public otoroshi.next.plugins.grpc.ServiceResponse.Builder addServiceBuilder() {
      return getServiceFieldBuilder().addBuilder(
          otoroshi.next.plugins.grpc.ServiceResponse.getDefaultInstance());
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public otoroshi.next.plugins.grpc.ServiceResponse.Builder addServiceBuilder(
        int index) {
      return getServiceFieldBuilder().addBuilder(
          index, otoroshi.next.plugins.grpc.ServiceResponse.getDefaultInstance());
    }
    /**
     * <pre>
     * The information of each service may be expanded in the future, so we use
     * ServiceResponse message to encapsulate it.
     * </pre>
     *
     * <code>repeated .grpc.reflection.v1alpha.ServiceResponse service = 1;</code>
     */
    public java.util.List<otoroshi.next.plugins.grpc.ServiceResponse.Builder> 
         getServiceBuilderList() {
      return getServiceFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        otoroshi.next.plugins.grpc.ServiceResponse, otoroshi.next.plugins.grpc.ServiceResponse.Builder, otoroshi.next.plugins.grpc.ServiceResponseOrBuilder> 
        getServiceFieldBuilder() {
      if (serviceBuilder_ == null) {
        serviceBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            otoroshi.next.plugins.grpc.ServiceResponse, otoroshi.next.plugins.grpc.ServiceResponse.Builder, otoroshi.next.plugins.grpc.ServiceResponseOrBuilder>(
                service_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        service_ = null;
      }
      return serviceBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.ListServiceResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.ListServiceResponse)
  private static final otoroshi.next.plugins.grpc.ListServiceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new otoroshi.next.plugins.grpc.ListServiceResponse();
  }

  public static otoroshi.next.plugins.grpc.ListServiceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListServiceResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListServiceResponse>() {
    @java.lang.Override
    public ListServiceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListServiceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListServiceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public otoroshi.next.plugins.grpc.ListServiceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

