// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reflection.proto

package otoroshi.next.plugins.grpc;

/**
 * <pre>
 * The message sent by the client when calling ServerReflectionInfo method.
 * </pre>
 *
 * Protobuf type {@code grpc.reflection.v1alpha.ServerReflectionRequest}
 */
public final class ServerReflectionRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.ServerReflectionRequest)
    ServerReflectionRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerReflectionRequest.newBuilder() to construct.
  private ServerReflectionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerReflectionRequest() {
    host_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerReflectionRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            otoroshi.next.plugins.grpc.ServerReflectionRequest.class, otoroshi.next.plugins.grpc.ServerReflectionRequest.Builder.class);
  }

  private int messageRequestCase_ = 0;
  private java.lang.Object messageRequest_;
  public enum MessageRequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FILE_BY_FILENAME(3),
    FILE_CONTAINING_SYMBOL(4),
    FILE_CONTAINING_EXTENSION(5),
    ALL_EXTENSION_NUMBERS_OF_TYPE(6),
    LIST_SERVICES(7),
    MESSAGEREQUEST_NOT_SET(0);
    private final int value;
    private MessageRequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageRequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageRequestCase forNumber(int value) {
      switch (value) {
        case 3: return FILE_BY_FILENAME;
        case 4: return FILE_CONTAINING_SYMBOL;
        case 5: return FILE_CONTAINING_EXTENSION;
        case 6: return ALL_EXTENSION_NUMBERS_OF_TYPE;
        case 7: return LIST_SERVICES;
        case 0: return MESSAGEREQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageRequestCase
  getMessageRequestCase() {
    return MessageRequestCase.forNumber(
        messageRequestCase_);
  }

  public static final int HOST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object host_ = "";
  /**
   * <code>string host = 1;</code>
   * @return The host.
   */
  @java.lang.Override
  public java.lang.String getHost() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      host_ = s;
      return s;
    }
  }
  /**
   * <code>string host = 1;</code>
   * @return The bytes for host.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostBytes() {
    java.lang.Object ref = host_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      host_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_BY_FILENAME_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Find a proto file by the file name.
   * </pre>
   *
   * <code>string file_by_filename = 3;</code>
   * @return Whether the fileByFilename field is set.
   */
  public boolean hasFileByFilename() {
    return messageRequestCase_ == 3;
  }
  /**
   * <pre>
   * Find a proto file by the file name.
   * </pre>
   *
   * <code>string file_by_filename = 3;</code>
   * @return The fileByFilename.
   */
  public java.lang.String getFileByFilename() {
    java.lang.Object ref = "";
    if (messageRequestCase_ == 3) {
      ref = messageRequest_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (messageRequestCase_ == 3) {
        messageRequest_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Find a proto file by the file name.
   * </pre>
   *
   * <code>string file_by_filename = 3;</code>
   * @return The bytes for fileByFilename.
   */
  public com.google.protobuf.ByteString
      getFileByFilenameBytes() {
    java.lang.Object ref = "";
    if (messageRequestCase_ == 3) {
      ref = messageRequest_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (messageRequestCase_ == 3) {
        messageRequest_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_CONTAINING_SYMBOL_FIELD_NUMBER = 4;
  /**
   * <pre>
   * Find the proto file that declares the given fully-qualified symbol name.
   * This field should be a fully-qualified symbol name
   * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
   * </pre>
   *
   * <code>string file_containing_symbol = 4;</code>
   * @return Whether the fileContainingSymbol field is set.
   */
  public boolean hasFileContainingSymbol() {
    return messageRequestCase_ == 4;
  }
  /**
   * <pre>
   * Find the proto file that declares the given fully-qualified symbol name.
   * This field should be a fully-qualified symbol name
   * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
   * </pre>
   *
   * <code>string file_containing_symbol = 4;</code>
   * @return The fileContainingSymbol.
   */
  public java.lang.String getFileContainingSymbol() {
    java.lang.Object ref = "";
    if (messageRequestCase_ == 4) {
      ref = messageRequest_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (messageRequestCase_ == 4) {
        messageRequest_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Find the proto file that declares the given fully-qualified symbol name.
   * This field should be a fully-qualified symbol name
   * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
   * </pre>
   *
   * <code>string file_containing_symbol = 4;</code>
   * @return The bytes for fileContainingSymbol.
   */
  public com.google.protobuf.ByteString
      getFileContainingSymbolBytes() {
    java.lang.Object ref = "";
    if (messageRequestCase_ == 4) {
      ref = messageRequest_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (messageRequestCase_ == 4) {
        messageRequest_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_CONTAINING_EXTENSION_FIELD_NUMBER = 5;
  /**
   * <pre>
   * Find the proto file which defines an extension extending the given
   * message type with the given field number.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
   * @return Whether the fileContainingExtension field is set.
   */
  @java.lang.Override
  public boolean hasFileContainingExtension() {
    return messageRequestCase_ == 5;
  }
  /**
   * <pre>
   * Find the proto file which defines an extension extending the given
   * message type with the given field number.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
   * @return The fileContainingExtension.
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ExtensionRequest getFileContainingExtension() {
    if (messageRequestCase_ == 5) {
       return (otoroshi.next.plugins.grpc.ExtensionRequest) messageRequest_;
    }
    return otoroshi.next.plugins.grpc.ExtensionRequest.getDefaultInstance();
  }
  /**
   * <pre>
   * Find the proto file which defines an extension extending the given
   * message type with the given field number.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ExtensionRequestOrBuilder getFileContainingExtensionOrBuilder() {
    if (messageRequestCase_ == 5) {
       return (otoroshi.next.plugins.grpc.ExtensionRequest) messageRequest_;
    }
    return otoroshi.next.plugins.grpc.ExtensionRequest.getDefaultInstance();
  }

  public static final int ALL_EXTENSION_NUMBERS_OF_TYPE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * Finds the tag numbers used by all known extensions of extendee_type, and
   * appends them to ExtensionNumberResponse in an undefined order.
   * Its corresponding method is best-effort: it's not guaranteed that the
   * reflection service will implement this method, and it's not guaranteed
   * that this method will provide all extensions. Returns
   * StatusCode::UNIMPLEMENTED if it's not implemented.
   * This field should be a fully-qualified type name. The format is
   * &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string all_extension_numbers_of_type = 6;</code>
   * @return Whether the allExtensionNumbersOfType field is set.
   */
  public boolean hasAllExtensionNumbersOfType() {
    return messageRequestCase_ == 6;
  }
  /**
   * <pre>
   * Finds the tag numbers used by all known extensions of extendee_type, and
   * appends them to ExtensionNumberResponse in an undefined order.
   * Its corresponding method is best-effort: it's not guaranteed that the
   * reflection service will implement this method, and it's not guaranteed
   * that this method will provide all extensions. Returns
   * StatusCode::UNIMPLEMENTED if it's not implemented.
   * This field should be a fully-qualified type name. The format is
   * &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string all_extension_numbers_of_type = 6;</code>
   * @return The allExtensionNumbersOfType.
   */
  public java.lang.String getAllExtensionNumbersOfType() {
    java.lang.Object ref = "";
    if (messageRequestCase_ == 6) {
      ref = messageRequest_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (messageRequestCase_ == 6) {
        messageRequest_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Finds the tag numbers used by all known extensions of extendee_type, and
   * appends them to ExtensionNumberResponse in an undefined order.
   * Its corresponding method is best-effort: it's not guaranteed that the
   * reflection service will implement this method, and it's not guaranteed
   * that this method will provide all extensions. Returns
   * StatusCode::UNIMPLEMENTED if it's not implemented.
   * This field should be a fully-qualified type name. The format is
   * &lt;package&gt;.&lt;type&gt;
   * </pre>
   *
   * <code>string all_extension_numbers_of_type = 6;</code>
   * @return The bytes for allExtensionNumbersOfType.
   */
  public com.google.protobuf.ByteString
      getAllExtensionNumbersOfTypeBytes() {
    java.lang.Object ref = "";
    if (messageRequestCase_ == 6) {
      ref = messageRequest_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (messageRequestCase_ == 6) {
        messageRequest_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIST_SERVICES_FIELD_NUMBER = 7;
  /**
   * <pre>
   * List the full names of registered services. The content will not be
   * checked.
   * </pre>
   *
   * <code>string list_services = 7;</code>
   * @return Whether the listServices field is set.
   */
  public boolean hasListServices() {
    return messageRequestCase_ == 7;
  }
  /**
   * <pre>
   * List the full names of registered services. The content will not be
   * checked.
   * </pre>
   *
   * <code>string list_services = 7;</code>
   * @return The listServices.
   */
  public java.lang.String getListServices() {
    java.lang.Object ref = "";
    if (messageRequestCase_ == 7) {
      ref = messageRequest_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (messageRequestCase_ == 7) {
        messageRequest_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * List the full names of registered services. The content will not be
   * checked.
   * </pre>
   *
   * <code>string list_services = 7;</code>
   * @return The bytes for listServices.
   */
  public com.google.protobuf.ByteString
      getListServicesBytes() {
    java.lang.Object ref = "";
    if (messageRequestCase_ == 7) {
      ref = messageRequest_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (messageRequestCase_ == 7) {
        messageRequest_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
    }
    if (messageRequestCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, messageRequest_);
    }
    if (messageRequestCase_ == 4) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageRequest_);
    }
    if (messageRequestCase_ == 5) {
      output.writeMessage(5, (otoroshi.next.plugins.grpc.ExtensionRequest) messageRequest_);
    }
    if (messageRequestCase_ == 6) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, messageRequest_);
    }
    if (messageRequestCase_ == 7) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, messageRequest_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(host_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
    }
    if (messageRequestCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, messageRequest_);
    }
    if (messageRequestCase_ == 4) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageRequest_);
    }
    if (messageRequestCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (otoroshi.next.plugins.grpc.ExtensionRequest) messageRequest_);
    }
    if (messageRequestCase_ == 6) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, messageRequest_);
    }
    if (messageRequestCase_ == 7) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, messageRequest_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof otoroshi.next.plugins.grpc.ServerReflectionRequest)) {
      return super.equals(obj);
    }
    otoroshi.next.plugins.grpc.ServerReflectionRequest other = (otoroshi.next.plugins.grpc.ServerReflectionRequest) obj;

    if (!getHost()
        .equals(other.getHost())) return false;
    if (!getMessageRequestCase().equals(other.getMessageRequestCase())) return false;
    switch (messageRequestCase_) {
      case 3:
        if (!getFileByFilename()
            .equals(other.getFileByFilename())) return false;
        break;
      case 4:
        if (!getFileContainingSymbol()
            .equals(other.getFileContainingSymbol())) return false;
        break;
      case 5:
        if (!getFileContainingExtension()
            .equals(other.getFileContainingExtension())) return false;
        break;
      case 6:
        if (!getAllExtensionNumbersOfType()
            .equals(other.getAllExtensionNumbersOfType())) return false;
        break;
      case 7:
        if (!getListServices()
            .equals(other.getListServices())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOST_FIELD_NUMBER;
    hash = (53 * hash) + getHost().hashCode();
    switch (messageRequestCase_) {
      case 3:
        hash = (37 * hash) + FILE_BY_FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFileByFilename().hashCode();
        break;
      case 4:
        hash = (37 * hash) + FILE_CONTAINING_SYMBOL_FIELD_NUMBER;
        hash = (53 * hash) + getFileContainingSymbol().hashCode();
        break;
      case 5:
        hash = (37 * hash) + FILE_CONTAINING_EXTENSION_FIELD_NUMBER;
        hash = (53 * hash) + getFileContainingExtension().hashCode();
        break;
      case 6:
        hash = (37 * hash) + ALL_EXTENSION_NUMBERS_OF_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getAllExtensionNumbersOfType().hashCode();
        break;
      case 7:
        hash = (37 * hash) + LIST_SERVICES_FIELD_NUMBER;
        hash = (53 * hash) + getListServices().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(otoroshi.next.plugins.grpc.ServerReflectionRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The message sent by the client when calling ServerReflectionInfo method.
   * </pre>
   *
   * Protobuf type {@code grpc.reflection.v1alpha.ServerReflectionRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.ServerReflectionRequest)
      otoroshi.next.plugins.grpc.ServerReflectionRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              otoroshi.next.plugins.grpc.ServerReflectionRequest.class, otoroshi.next.plugins.grpc.ServerReflectionRequest.Builder.class);
    }

    // Construct using otoroshi.next.plugins.grpc.ServerReflectionRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      host_ = "";
      if (fileContainingExtensionBuilder_ != null) {
        fileContainingExtensionBuilder_.clear();
      }
      messageRequestCase_ = 0;
      messageRequest_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionRequest_descriptor;
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ServerReflectionRequest getDefaultInstanceForType() {
      return otoroshi.next.plugins.grpc.ServerReflectionRequest.getDefaultInstance();
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ServerReflectionRequest build() {
      otoroshi.next.plugins.grpc.ServerReflectionRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ServerReflectionRequest buildPartial() {
      otoroshi.next.plugins.grpc.ServerReflectionRequest result = new otoroshi.next.plugins.grpc.ServerReflectionRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(otoroshi.next.plugins.grpc.ServerReflectionRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.host_ = host_;
      }
    }

    private void buildPartialOneofs(otoroshi.next.plugins.grpc.ServerReflectionRequest result) {
      result.messageRequestCase_ = messageRequestCase_;
      result.messageRequest_ = this.messageRequest_;
      if (messageRequestCase_ == 5 &&
          fileContainingExtensionBuilder_ != null) {
        result.messageRequest_ = fileContainingExtensionBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof otoroshi.next.plugins.grpc.ServerReflectionRequest) {
        return mergeFrom((otoroshi.next.plugins.grpc.ServerReflectionRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(otoroshi.next.plugins.grpc.ServerReflectionRequest other) {
      if (other == otoroshi.next.plugins.grpc.ServerReflectionRequest.getDefaultInstance()) return this;
      if (!other.getHost().isEmpty()) {
        host_ = other.host_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      switch (other.getMessageRequestCase()) {
        case FILE_BY_FILENAME: {
          messageRequestCase_ = 3;
          messageRequest_ = other.messageRequest_;
          onChanged();
          break;
        }
        case FILE_CONTAINING_SYMBOL: {
          messageRequestCase_ = 4;
          messageRequest_ = other.messageRequest_;
          onChanged();
          break;
        }
        case FILE_CONTAINING_EXTENSION: {
          mergeFileContainingExtension(other.getFileContainingExtension());
          break;
        }
        case ALL_EXTENSION_NUMBERS_OF_TYPE: {
          messageRequestCase_ = 6;
          messageRequest_ = other.messageRequest_;
          onChanged();
          break;
        }
        case LIST_SERVICES: {
          messageRequestCase_ = 7;
          messageRequest_ = other.messageRequest_;
          onChanged();
          break;
        }
        case MESSAGEREQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              host_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              messageRequestCase_ = 3;
              messageRequest_ = s;
              break;
            } // case 26
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              messageRequestCase_ = 4;
              messageRequest_ = s;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getFileContainingExtensionFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageRequestCase_ = 5;
              break;
            } // case 42
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();
              messageRequestCase_ = 6;
              messageRequest_ = s;
              break;
            } // case 50
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              messageRequestCase_ = 7;
              messageRequest_ = s;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageRequestCase_ = 0;
    private java.lang.Object messageRequest_;
    public MessageRequestCase
        getMessageRequestCase() {
      return MessageRequestCase.forNumber(
          messageRequestCase_);
    }

    public Builder clearMessageRequest() {
      messageRequestCase_ = 0;
      messageRequest_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object host_ = "";
    /**
     * <code>string host = 1;</code>
     * @return The host.
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string host = 1;</code>
     * @return The bytes for host.
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string host = 1;</code>
     * @param value The host to set.
     * @return This builder for chaining.
     */
    public Builder setHost(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      host_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string host = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHost() {
      host_ = getDefaultInstance().getHost();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string host = 1;</code>
     * @param value The bytes for host to set.
     * @return This builder for chaining.
     */
    public Builder setHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      host_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Find a proto file by the file name.
     * </pre>
     *
     * <code>string file_by_filename = 3;</code>
     * @return Whether the fileByFilename field is set.
     */
    @java.lang.Override
    public boolean hasFileByFilename() {
      return messageRequestCase_ == 3;
    }
    /**
     * <pre>
     * Find a proto file by the file name.
     * </pre>
     *
     * <code>string file_by_filename = 3;</code>
     * @return The fileByFilename.
     */
    @java.lang.Override
    public java.lang.String getFileByFilename() {
      java.lang.Object ref = "";
      if (messageRequestCase_ == 3) {
        ref = messageRequest_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (messageRequestCase_ == 3) {
          messageRequest_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Find a proto file by the file name.
     * </pre>
     *
     * <code>string file_by_filename = 3;</code>
     * @return The bytes for fileByFilename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileByFilenameBytes() {
      java.lang.Object ref = "";
      if (messageRequestCase_ == 3) {
        ref = messageRequest_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (messageRequestCase_ == 3) {
          messageRequest_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Find a proto file by the file name.
     * </pre>
     *
     * <code>string file_by_filename = 3;</code>
     * @param value The fileByFilename to set.
     * @return This builder for chaining.
     */
    public Builder setFileByFilename(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageRequestCase_ = 3;
      messageRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Find a proto file by the file name.
     * </pre>
     *
     * <code>string file_by_filename = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileByFilename() {
      if (messageRequestCase_ == 3) {
        messageRequestCase_ = 0;
        messageRequest_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Find a proto file by the file name.
     * </pre>
     *
     * <code>string file_by_filename = 3;</code>
     * @param value The bytes for fileByFilename to set.
     * @return This builder for chaining.
     */
    public Builder setFileByFilenameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageRequestCase_ = 3;
      messageRequest_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * Find the proto file that declares the given fully-qualified symbol name.
     * This field should be a fully-qualified symbol name
     * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
     * </pre>
     *
     * <code>string file_containing_symbol = 4;</code>
     * @return Whether the fileContainingSymbol field is set.
     */
    @java.lang.Override
    public boolean hasFileContainingSymbol() {
      return messageRequestCase_ == 4;
    }
    /**
     * <pre>
     * Find the proto file that declares the given fully-qualified symbol name.
     * This field should be a fully-qualified symbol name
     * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
     * </pre>
     *
     * <code>string file_containing_symbol = 4;</code>
     * @return The fileContainingSymbol.
     */
    @java.lang.Override
    public java.lang.String getFileContainingSymbol() {
      java.lang.Object ref = "";
      if (messageRequestCase_ == 4) {
        ref = messageRequest_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (messageRequestCase_ == 4) {
          messageRequest_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Find the proto file that declares the given fully-qualified symbol name.
     * This field should be a fully-qualified symbol name
     * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
     * </pre>
     *
     * <code>string file_containing_symbol = 4;</code>
     * @return The bytes for fileContainingSymbol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileContainingSymbolBytes() {
      java.lang.Object ref = "";
      if (messageRequestCase_ == 4) {
        ref = messageRequest_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (messageRequestCase_ == 4) {
          messageRequest_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Find the proto file that declares the given fully-qualified symbol name.
     * This field should be a fully-qualified symbol name
     * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
     * </pre>
     *
     * <code>string file_containing_symbol = 4;</code>
     * @param value The fileContainingSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setFileContainingSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageRequestCase_ = 4;
      messageRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Find the proto file that declares the given fully-qualified symbol name.
     * This field should be a fully-qualified symbol name
     * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
     * </pre>
     *
     * <code>string file_containing_symbol = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileContainingSymbol() {
      if (messageRequestCase_ == 4) {
        messageRequestCase_ = 0;
        messageRequest_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Find the proto file that declares the given fully-qualified symbol name.
     * This field should be a fully-qualified symbol name
     * (e.g. &lt;package&gt;.&lt;service&gt;[.&lt;method&gt;] or &lt;package&gt;.&lt;type&gt;).
     * </pre>
     *
     * <code>string file_containing_symbol = 4;</code>
     * @param value The bytes for fileContainingSymbol to set.
     * @return This builder for chaining.
     */
    public Builder setFileContainingSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageRequestCase_ = 4;
      messageRequest_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ExtensionRequest, otoroshi.next.plugins.grpc.ExtensionRequest.Builder, otoroshi.next.plugins.grpc.ExtensionRequestOrBuilder> fileContainingExtensionBuilder_;
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     * @return Whether the fileContainingExtension field is set.
     */
    @java.lang.Override
    public boolean hasFileContainingExtension() {
      return messageRequestCase_ == 5;
    }
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     * @return The fileContainingExtension.
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.ExtensionRequest getFileContainingExtension() {
      if (fileContainingExtensionBuilder_ == null) {
        if (messageRequestCase_ == 5) {
          return (otoroshi.next.plugins.grpc.ExtensionRequest) messageRequest_;
        }
        return otoroshi.next.plugins.grpc.ExtensionRequest.getDefaultInstance();
      } else {
        if (messageRequestCase_ == 5) {
          return fileContainingExtensionBuilder_.getMessage();
        }
        return otoroshi.next.plugins.grpc.ExtensionRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     */
    public Builder setFileContainingExtension(otoroshi.next.plugins.grpc.ExtensionRequest value) {
      if (fileContainingExtensionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageRequest_ = value;
        onChanged();
      } else {
        fileContainingExtensionBuilder_.setMessage(value);
      }
      messageRequestCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     */
    public Builder setFileContainingExtension(
        otoroshi.next.plugins.grpc.ExtensionRequest.Builder builderForValue) {
      if (fileContainingExtensionBuilder_ == null) {
        messageRequest_ = builderForValue.build();
        onChanged();
      } else {
        fileContainingExtensionBuilder_.setMessage(builderForValue.build());
      }
      messageRequestCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     */
    public Builder mergeFileContainingExtension(otoroshi.next.plugins.grpc.ExtensionRequest value) {
      if (fileContainingExtensionBuilder_ == null) {
        if (messageRequestCase_ == 5 &&
            messageRequest_ != otoroshi.next.plugins.grpc.ExtensionRequest.getDefaultInstance()) {
          messageRequest_ = otoroshi.next.plugins.grpc.ExtensionRequest.newBuilder((otoroshi.next.plugins.grpc.ExtensionRequest) messageRequest_)
              .mergeFrom(value).buildPartial();
        } else {
          messageRequest_ = value;
        }
        onChanged();
      } else {
        if (messageRequestCase_ == 5) {
          fileContainingExtensionBuilder_.mergeFrom(value);
        } else {
          fileContainingExtensionBuilder_.setMessage(value);
        }
      }
      messageRequestCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     */
    public Builder clearFileContainingExtension() {
      if (fileContainingExtensionBuilder_ == null) {
        if (messageRequestCase_ == 5) {
          messageRequestCase_ = 0;
          messageRequest_ = null;
          onChanged();
        }
      } else {
        if (messageRequestCase_ == 5) {
          messageRequestCase_ = 0;
          messageRequest_ = null;
        }
        fileContainingExtensionBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     */
    public otoroshi.next.plugins.grpc.ExtensionRequest.Builder getFileContainingExtensionBuilder() {
      return getFileContainingExtensionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.ExtensionRequestOrBuilder getFileContainingExtensionOrBuilder() {
      if ((messageRequestCase_ == 5) && (fileContainingExtensionBuilder_ != null)) {
        return fileContainingExtensionBuilder_.getMessageOrBuilder();
      } else {
        if (messageRequestCase_ == 5) {
          return (otoroshi.next.plugins.grpc.ExtensionRequest) messageRequest_;
        }
        return otoroshi.next.plugins.grpc.ExtensionRequest.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Find the proto file which defines an extension extending the given
     * message type with the given field number.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionRequest file_containing_extension = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ExtensionRequest, otoroshi.next.plugins.grpc.ExtensionRequest.Builder, otoroshi.next.plugins.grpc.ExtensionRequestOrBuilder> 
        getFileContainingExtensionFieldBuilder() {
      if (fileContainingExtensionBuilder_ == null) {
        if (!(messageRequestCase_ == 5)) {
          messageRequest_ = otoroshi.next.plugins.grpc.ExtensionRequest.getDefaultInstance();
        }
        fileContainingExtensionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            otoroshi.next.plugins.grpc.ExtensionRequest, otoroshi.next.plugins.grpc.ExtensionRequest.Builder, otoroshi.next.plugins.grpc.ExtensionRequestOrBuilder>(
                (otoroshi.next.plugins.grpc.ExtensionRequest) messageRequest_,
                getParentForChildren(),
                isClean());
        messageRequest_ = null;
      }
      messageRequestCase_ = 5;
      onChanged();
      return fileContainingExtensionBuilder_;
    }

    /**
     * <pre>
     * Finds the tag numbers used by all known extensions of extendee_type, and
     * appends them to ExtensionNumberResponse in an undefined order.
     * Its corresponding method is best-effort: it's not guaranteed that the
     * reflection service will implement this method, and it's not guaranteed
     * that this method will provide all extensions. Returns
     * StatusCode::UNIMPLEMENTED if it's not implemented.
     * This field should be a fully-qualified type name. The format is
     * &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string all_extension_numbers_of_type = 6;</code>
     * @return Whether the allExtensionNumbersOfType field is set.
     */
    @java.lang.Override
    public boolean hasAllExtensionNumbersOfType() {
      return messageRequestCase_ == 6;
    }
    /**
     * <pre>
     * Finds the tag numbers used by all known extensions of extendee_type, and
     * appends them to ExtensionNumberResponse in an undefined order.
     * Its corresponding method is best-effort: it's not guaranteed that the
     * reflection service will implement this method, and it's not guaranteed
     * that this method will provide all extensions. Returns
     * StatusCode::UNIMPLEMENTED if it's not implemented.
     * This field should be a fully-qualified type name. The format is
     * &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string all_extension_numbers_of_type = 6;</code>
     * @return The allExtensionNumbersOfType.
     */
    @java.lang.Override
    public java.lang.String getAllExtensionNumbersOfType() {
      java.lang.Object ref = "";
      if (messageRequestCase_ == 6) {
        ref = messageRequest_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (messageRequestCase_ == 6) {
          messageRequest_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Finds the tag numbers used by all known extensions of extendee_type, and
     * appends them to ExtensionNumberResponse in an undefined order.
     * Its corresponding method is best-effort: it's not guaranteed that the
     * reflection service will implement this method, and it's not guaranteed
     * that this method will provide all extensions. Returns
     * StatusCode::UNIMPLEMENTED if it's not implemented.
     * This field should be a fully-qualified type name. The format is
     * &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string all_extension_numbers_of_type = 6;</code>
     * @return The bytes for allExtensionNumbersOfType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAllExtensionNumbersOfTypeBytes() {
      java.lang.Object ref = "";
      if (messageRequestCase_ == 6) {
        ref = messageRequest_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (messageRequestCase_ == 6) {
          messageRequest_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Finds the tag numbers used by all known extensions of extendee_type, and
     * appends them to ExtensionNumberResponse in an undefined order.
     * Its corresponding method is best-effort: it's not guaranteed that the
     * reflection service will implement this method, and it's not guaranteed
     * that this method will provide all extensions. Returns
     * StatusCode::UNIMPLEMENTED if it's not implemented.
     * This field should be a fully-qualified type name. The format is
     * &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string all_extension_numbers_of_type = 6;</code>
     * @param value The allExtensionNumbersOfType to set.
     * @return This builder for chaining.
     */
    public Builder setAllExtensionNumbersOfType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageRequestCase_ = 6;
      messageRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Finds the tag numbers used by all known extensions of extendee_type, and
     * appends them to ExtensionNumberResponse in an undefined order.
     * Its corresponding method is best-effort: it's not guaranteed that the
     * reflection service will implement this method, and it's not guaranteed
     * that this method will provide all extensions. Returns
     * StatusCode::UNIMPLEMENTED if it's not implemented.
     * This field should be a fully-qualified type name. The format is
     * &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string all_extension_numbers_of_type = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAllExtensionNumbersOfType() {
      if (messageRequestCase_ == 6) {
        messageRequestCase_ = 0;
        messageRequest_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Finds the tag numbers used by all known extensions of extendee_type, and
     * appends them to ExtensionNumberResponse in an undefined order.
     * Its corresponding method is best-effort: it's not guaranteed that the
     * reflection service will implement this method, and it's not guaranteed
     * that this method will provide all extensions. Returns
     * StatusCode::UNIMPLEMENTED if it's not implemented.
     * This field should be a fully-qualified type name. The format is
     * &lt;package&gt;.&lt;type&gt;
     * </pre>
     *
     * <code>string all_extension_numbers_of_type = 6;</code>
     * @param value The bytes for allExtensionNumbersOfType to set.
     * @return This builder for chaining.
     */
    public Builder setAllExtensionNumbersOfTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageRequestCase_ = 6;
      messageRequest_ = value;
      onChanged();
      return this;
    }

    /**
     * <pre>
     * List the full names of registered services. The content will not be
     * checked.
     * </pre>
     *
     * <code>string list_services = 7;</code>
     * @return Whether the listServices field is set.
     */
    @java.lang.Override
    public boolean hasListServices() {
      return messageRequestCase_ == 7;
    }
    /**
     * <pre>
     * List the full names of registered services. The content will not be
     * checked.
     * </pre>
     *
     * <code>string list_services = 7;</code>
     * @return The listServices.
     */
    @java.lang.Override
    public java.lang.String getListServices() {
      java.lang.Object ref = "";
      if (messageRequestCase_ == 7) {
        ref = messageRequest_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (messageRequestCase_ == 7) {
          messageRequest_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * List the full names of registered services. The content will not be
     * checked.
     * </pre>
     *
     * <code>string list_services = 7;</code>
     * @return The bytes for listServices.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getListServicesBytes() {
      java.lang.Object ref = "";
      if (messageRequestCase_ == 7) {
        ref = messageRequest_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (messageRequestCase_ == 7) {
          messageRequest_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * List the full names of registered services. The content will not be
     * checked.
     * </pre>
     *
     * <code>string list_services = 7;</code>
     * @param value The listServices to set.
     * @return This builder for chaining.
     */
    public Builder setListServices(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      messageRequestCase_ = 7;
      messageRequest_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * List the full names of registered services. The content will not be
     * checked.
     * </pre>
     *
     * <code>string list_services = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearListServices() {
      if (messageRequestCase_ == 7) {
        messageRequestCase_ = 0;
        messageRequest_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * List the full names of registered services. The content will not be
     * checked.
     * </pre>
     *
     * <code>string list_services = 7;</code>
     * @param value The bytes for listServices to set.
     * @return This builder for chaining.
     */
    public Builder setListServicesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      messageRequestCase_ = 7;
      messageRequest_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.ServerReflectionRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.ServerReflectionRequest)
  private static final otoroshi.next.plugins.grpc.ServerReflectionRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new otoroshi.next.plugins.grpc.ServerReflectionRequest();
  }

  public static otoroshi.next.plugins.grpc.ServerReflectionRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerReflectionRequest>
      PARSER = new com.google.protobuf.AbstractParser<ServerReflectionRequest>() {
    @java.lang.Override
    public ServerReflectionRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerReflectionRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerReflectionRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public otoroshi.next.plugins.grpc.ServerReflectionRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

