// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reflection.proto

package otoroshi.next.plugins.grpc;

/**
 * <pre>
 * The message sent by the server to answer ServerReflectionInfo method.
 * </pre>
 *
 * Protobuf type {@code grpc.reflection.v1alpha.ServerReflectionResponse}
 */
public final class ServerReflectionResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.reflection.v1alpha.ServerReflectionResponse)
    ServerReflectionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerReflectionResponse.newBuilder() to construct.
  private ServerReflectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerReflectionResponse() {
    validHost_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerReflectionResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            otoroshi.next.plugins.grpc.ServerReflectionResponse.class, otoroshi.next.plugins.grpc.ServerReflectionResponse.Builder.class);
  }

  private int messageResponseCase_ = 0;
  private java.lang.Object messageResponse_;
  public enum MessageResponseCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    FILE_DESCRIPTOR_RESPONSE(4),
    ALL_EXTENSION_NUMBERS_RESPONSE(5),
    LIST_SERVICES_RESPONSE(6),
    ERROR_RESPONSE(7),
    MESSAGERESPONSE_NOT_SET(0);
    private final int value;
    private MessageResponseCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageResponseCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageResponseCase forNumber(int value) {
      switch (value) {
        case 4: return FILE_DESCRIPTOR_RESPONSE;
        case 5: return ALL_EXTENSION_NUMBERS_RESPONSE;
        case 6: return LIST_SERVICES_RESPONSE;
        case 7: return ERROR_RESPONSE;
        case 0: return MESSAGERESPONSE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageResponseCase
  getMessageResponseCase() {
    return MessageResponseCase.forNumber(
        messageResponseCase_);
  }

  public static final int VALID_HOST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object validHost_ = "";
  /**
   * <code>string valid_host = 1;</code>
   * @return The validHost.
   */
  @java.lang.Override
  public java.lang.String getValidHost() {
    java.lang.Object ref = validHost_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      validHost_ = s;
      return s;
    }
  }
  /**
   * <code>string valid_host = 1;</code>
   * @return The bytes for validHost.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValidHostBytes() {
    java.lang.Object ref = validHost_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      validHost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORIGINAL_REQUEST_FIELD_NUMBER = 2;
  private otoroshi.next.plugins.grpc.ServerReflectionRequest originalRequest_;
  /**
   * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
   * @return Whether the originalRequest field is set.
   */
  @java.lang.Override
  public boolean hasOriginalRequest() {
    return originalRequest_ != null;
  }
  /**
   * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
   * @return The originalRequest.
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ServerReflectionRequest getOriginalRequest() {
    return originalRequest_ == null ? otoroshi.next.plugins.grpc.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
  }
  /**
   * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ServerReflectionRequestOrBuilder getOriginalRequestOrBuilder() {
    return originalRequest_ == null ? otoroshi.next.plugins.grpc.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
  }

  public static final int FILE_DESCRIPTOR_RESPONSE_FIELD_NUMBER = 4;
  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies. As
   * the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
   * @return Whether the fileDescriptorResponse field is set.
   */
  @java.lang.Override
  public boolean hasFileDescriptorResponse() {
    return messageResponseCase_ == 4;
  }
  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies. As
   * the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
   * @return The fileDescriptorResponse.
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.FileDescriptorResponse getFileDescriptorResponse() {
    if (messageResponseCase_ == 4) {
       return (otoroshi.next.plugins.grpc.FileDescriptorResponse) messageResponse_;
    }
    return otoroshi.next.plugins.grpc.FileDescriptorResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * This message is used to answer file_by_filename, file_containing_symbol,
   * file_containing_extension requests with transitive dependencies. As
   * the repeated label is not allowed in oneof fields, we use a
   * FileDescriptorResponse message to encapsulate the repeated fields.
   * The reflection service is allowed to avoid sending FileDescriptorProtos
   * that were previously sent in response to earlier requests in the stream.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.FileDescriptorResponseOrBuilder getFileDescriptorResponseOrBuilder() {
    if (messageResponseCase_ == 4) {
       return (otoroshi.next.plugins.grpc.FileDescriptorResponse) messageResponse_;
    }
    return otoroshi.next.plugins.grpc.FileDescriptorResponse.getDefaultInstance();
  }

  public static final int ALL_EXTENSION_NUMBERS_RESPONSE_FIELD_NUMBER = 5;
  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requst.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   * @return Whether the allExtensionNumbersResponse field is set.
   */
  @java.lang.Override
  public boolean hasAllExtensionNumbersResponse() {
    return messageResponseCase_ == 5;
  }
  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requst.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   * @return The allExtensionNumbersResponse.
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ExtensionNumberResponse getAllExtensionNumbersResponse() {
    if (messageResponseCase_ == 5) {
       return (otoroshi.next.plugins.grpc.ExtensionNumberResponse) messageResponse_;
    }
    return otoroshi.next.plugins.grpc.ExtensionNumberResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * This message is used to answer all_extension_numbers_of_type requst.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ExtensionNumberResponseOrBuilder getAllExtensionNumbersResponseOrBuilder() {
    if (messageResponseCase_ == 5) {
       return (otoroshi.next.plugins.grpc.ExtensionNumberResponse) messageResponse_;
    }
    return otoroshi.next.plugins.grpc.ExtensionNumberResponse.getDefaultInstance();
  }

  public static final int LIST_SERVICES_RESPONSE_FIELD_NUMBER = 6;
  /**
   * <pre>
   * This message is used to answer list_services request.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
   * @return Whether the listServicesResponse field is set.
   */
  @java.lang.Override
  public boolean hasListServicesResponse() {
    return messageResponseCase_ == 6;
  }
  /**
   * <pre>
   * This message is used to answer list_services request.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
   * @return The listServicesResponse.
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ListServiceResponse getListServicesResponse() {
    if (messageResponseCase_ == 6) {
       return (otoroshi.next.plugins.grpc.ListServiceResponse) messageResponse_;
    }
    return otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * This message is used to answer list_services request.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ListServiceResponseOrBuilder getListServicesResponseOrBuilder() {
    if (messageResponseCase_ == 6) {
       return (otoroshi.next.plugins.grpc.ListServiceResponse) messageResponse_;
    }
    return otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance();
  }

  public static final int ERROR_RESPONSE_FIELD_NUMBER = 7;
  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
   * @return Whether the errorResponse field is set.
   */
  @java.lang.Override
  public boolean hasErrorResponse() {
    return messageResponseCase_ == 7;
  }
  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
   * @return The errorResponse.
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ErrorResponse getErrorResponse() {
    if (messageResponseCase_ == 7) {
       return (otoroshi.next.plugins.grpc.ErrorResponse) messageResponse_;
    }
    return otoroshi.next.plugins.grpc.ErrorResponse.getDefaultInstance();
  }
  /**
   * <pre>
   * This message is used when an error occurs.
   * </pre>
   *
   * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
   */
  @java.lang.Override
  public otoroshi.next.plugins.grpc.ErrorResponseOrBuilder getErrorResponseOrBuilder() {
    if (messageResponseCase_ == 7) {
       return (otoroshi.next.plugins.grpc.ErrorResponse) messageResponse_;
    }
    return otoroshi.next.plugins.grpc.ErrorResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validHost_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, validHost_);
    }
    if (originalRequest_ != null) {
      output.writeMessage(2, getOriginalRequest());
    }
    if (messageResponseCase_ == 4) {
      output.writeMessage(4, (otoroshi.next.plugins.grpc.FileDescriptorResponse) messageResponse_);
    }
    if (messageResponseCase_ == 5) {
      output.writeMessage(5, (otoroshi.next.plugins.grpc.ExtensionNumberResponse) messageResponse_);
    }
    if (messageResponseCase_ == 6) {
      output.writeMessage(6, (otoroshi.next.plugins.grpc.ListServiceResponse) messageResponse_);
    }
    if (messageResponseCase_ == 7) {
      output.writeMessage(7, (otoroshi.next.plugins.grpc.ErrorResponse) messageResponse_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validHost_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, validHost_);
    }
    if (originalRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOriginalRequest());
    }
    if (messageResponseCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (otoroshi.next.plugins.grpc.FileDescriptorResponse) messageResponse_);
    }
    if (messageResponseCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (otoroshi.next.plugins.grpc.ExtensionNumberResponse) messageResponse_);
    }
    if (messageResponseCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (otoroshi.next.plugins.grpc.ListServiceResponse) messageResponse_);
    }
    if (messageResponseCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (otoroshi.next.plugins.grpc.ErrorResponse) messageResponse_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof otoroshi.next.plugins.grpc.ServerReflectionResponse)) {
      return super.equals(obj);
    }
    otoroshi.next.plugins.grpc.ServerReflectionResponse other = (otoroshi.next.plugins.grpc.ServerReflectionResponse) obj;

    if (!getValidHost()
        .equals(other.getValidHost())) return false;
    if (hasOriginalRequest() != other.hasOriginalRequest()) return false;
    if (hasOriginalRequest()) {
      if (!getOriginalRequest()
          .equals(other.getOriginalRequest())) return false;
    }
    if (!getMessageResponseCase().equals(other.getMessageResponseCase())) return false;
    switch (messageResponseCase_) {
      case 4:
        if (!getFileDescriptorResponse()
            .equals(other.getFileDescriptorResponse())) return false;
        break;
      case 5:
        if (!getAllExtensionNumbersResponse()
            .equals(other.getAllExtensionNumbersResponse())) return false;
        break;
      case 6:
        if (!getListServicesResponse()
            .equals(other.getListServicesResponse())) return false;
        break;
      case 7:
        if (!getErrorResponse()
            .equals(other.getErrorResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VALID_HOST_FIELD_NUMBER;
    hash = (53 * hash) + getValidHost().hashCode();
    if (hasOriginalRequest()) {
      hash = (37 * hash) + ORIGINAL_REQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getOriginalRequest().hashCode();
    }
    switch (messageResponseCase_) {
      case 4:
        hash = (37 * hash) + FILE_DESCRIPTOR_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getFileDescriptorResponse().hashCode();
        break;
      case 5:
        hash = (37 * hash) + ALL_EXTENSION_NUMBERS_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getAllExtensionNumbersResponse().hashCode();
        break;
      case 6:
        hash = (37 * hash) + LIST_SERVICES_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getListServicesResponse().hashCode();
        break;
      case 7:
        hash = (37 * hash) + ERROR_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static otoroshi.next.plugins.grpc.ServerReflectionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(otoroshi.next.plugins.grpc.ServerReflectionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The message sent by the server to answer ServerReflectionInfo method.
   * </pre>
   *
   * Protobuf type {@code grpc.reflection.v1alpha.ServerReflectionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.reflection.v1alpha.ServerReflectionResponse)
      otoroshi.next.plugins.grpc.ServerReflectionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              otoroshi.next.plugins.grpc.ServerReflectionResponse.class, otoroshi.next.plugins.grpc.ServerReflectionResponse.Builder.class);
    }

    // Construct using otoroshi.next.plugins.grpc.ServerReflectionResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      validHost_ = "";
      originalRequest_ = null;
      if (originalRequestBuilder_ != null) {
        originalRequestBuilder_.dispose();
        originalRequestBuilder_ = null;
      }
      if (fileDescriptorResponseBuilder_ != null) {
        fileDescriptorResponseBuilder_.clear();
      }
      if (allExtensionNumbersResponseBuilder_ != null) {
        allExtensionNumbersResponseBuilder_.clear();
      }
      if (listServicesResponseBuilder_ != null) {
        listServicesResponseBuilder_.clear();
      }
      if (errorResponseBuilder_ != null) {
        errorResponseBuilder_.clear();
      }
      messageResponseCase_ = 0;
      messageResponse_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return otoroshi.next.plugins.grpc.ServerReflectionProto.internal_static_grpc_reflection_v1alpha_ServerReflectionResponse_descriptor;
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ServerReflectionResponse getDefaultInstanceForType() {
      return otoroshi.next.plugins.grpc.ServerReflectionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ServerReflectionResponse build() {
      otoroshi.next.plugins.grpc.ServerReflectionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public otoroshi.next.plugins.grpc.ServerReflectionResponse buildPartial() {
      otoroshi.next.plugins.grpc.ServerReflectionResponse result = new otoroshi.next.plugins.grpc.ServerReflectionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(otoroshi.next.plugins.grpc.ServerReflectionResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.validHost_ = validHost_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.originalRequest_ = originalRequestBuilder_ == null
            ? originalRequest_
            : originalRequestBuilder_.build();
      }
    }

    private void buildPartialOneofs(otoroshi.next.plugins.grpc.ServerReflectionResponse result) {
      result.messageResponseCase_ = messageResponseCase_;
      result.messageResponse_ = this.messageResponse_;
      if (messageResponseCase_ == 4 &&
          fileDescriptorResponseBuilder_ != null) {
        result.messageResponse_ = fileDescriptorResponseBuilder_.build();
      }
      if (messageResponseCase_ == 5 &&
          allExtensionNumbersResponseBuilder_ != null) {
        result.messageResponse_ = allExtensionNumbersResponseBuilder_.build();
      }
      if (messageResponseCase_ == 6 &&
          listServicesResponseBuilder_ != null) {
        result.messageResponse_ = listServicesResponseBuilder_.build();
      }
      if (messageResponseCase_ == 7 &&
          errorResponseBuilder_ != null) {
        result.messageResponse_ = errorResponseBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof otoroshi.next.plugins.grpc.ServerReflectionResponse) {
        return mergeFrom((otoroshi.next.plugins.grpc.ServerReflectionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(otoroshi.next.plugins.grpc.ServerReflectionResponse other) {
      if (other == otoroshi.next.plugins.grpc.ServerReflectionResponse.getDefaultInstance()) return this;
      if (!other.getValidHost().isEmpty()) {
        validHost_ = other.validHost_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasOriginalRequest()) {
        mergeOriginalRequest(other.getOriginalRequest());
      }
      switch (other.getMessageResponseCase()) {
        case FILE_DESCRIPTOR_RESPONSE: {
          mergeFileDescriptorResponse(other.getFileDescriptorResponse());
          break;
        }
        case ALL_EXTENSION_NUMBERS_RESPONSE: {
          mergeAllExtensionNumbersResponse(other.getAllExtensionNumbersResponse());
          break;
        }
        case LIST_SERVICES_RESPONSE: {
          mergeListServicesResponse(other.getListServicesResponse());
          break;
        }
        case ERROR_RESPONSE: {
          mergeErrorResponse(other.getErrorResponse());
          break;
        }
        case MESSAGERESPONSE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              validHost_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getOriginalRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 34: {
              input.readMessage(
                  getFileDescriptorResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageResponseCase_ = 4;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getAllExtensionNumbersResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageResponseCase_ = 5;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getListServicesResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageResponseCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getErrorResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              messageResponseCase_ = 7;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int messageResponseCase_ = 0;
    private java.lang.Object messageResponse_;
    public MessageResponseCase
        getMessageResponseCase() {
      return MessageResponseCase.forNumber(
          messageResponseCase_);
    }

    public Builder clearMessageResponse() {
      messageResponseCase_ = 0;
      messageResponse_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object validHost_ = "";
    /**
     * <code>string valid_host = 1;</code>
     * @return The validHost.
     */
    public java.lang.String getValidHost() {
      java.lang.Object ref = validHost_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        validHost_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string valid_host = 1;</code>
     * @return The bytes for validHost.
     */
    public com.google.protobuf.ByteString
        getValidHostBytes() {
      java.lang.Object ref = validHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        validHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string valid_host = 1;</code>
     * @param value The validHost to set.
     * @return This builder for chaining.
     */
    public Builder setValidHost(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      validHost_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string valid_host = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValidHost() {
      validHost_ = getDefaultInstance().getValidHost();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string valid_host = 1;</code>
     * @param value The bytes for validHost to set.
     * @return This builder for chaining.
     */
    public Builder setValidHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      validHost_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private otoroshi.next.plugins.grpc.ServerReflectionRequest originalRequest_;
    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ServerReflectionRequest, otoroshi.next.plugins.grpc.ServerReflectionRequest.Builder, otoroshi.next.plugins.grpc.ServerReflectionRequestOrBuilder> originalRequestBuilder_;
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     * @return Whether the originalRequest field is set.
     */
    public boolean hasOriginalRequest() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     * @return The originalRequest.
     */
    public otoroshi.next.plugins.grpc.ServerReflectionRequest getOriginalRequest() {
      if (originalRequestBuilder_ == null) {
        return originalRequest_ == null ? otoroshi.next.plugins.grpc.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
      } else {
        return originalRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     */
    public Builder setOriginalRequest(otoroshi.next.plugins.grpc.ServerReflectionRequest value) {
      if (originalRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        originalRequest_ = value;
      } else {
        originalRequestBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     */
    public Builder setOriginalRequest(
        otoroshi.next.plugins.grpc.ServerReflectionRequest.Builder builderForValue) {
      if (originalRequestBuilder_ == null) {
        originalRequest_ = builderForValue.build();
      } else {
        originalRequestBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     */
    public Builder mergeOriginalRequest(otoroshi.next.plugins.grpc.ServerReflectionRequest value) {
      if (originalRequestBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          originalRequest_ != null &&
          originalRequest_ != otoroshi.next.plugins.grpc.ServerReflectionRequest.getDefaultInstance()) {
          getOriginalRequestBuilder().mergeFrom(value);
        } else {
          originalRequest_ = value;
        }
      } else {
        originalRequestBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     */
    public Builder clearOriginalRequest() {
      bitField0_ = (bitField0_ & ~0x00000002);
      originalRequest_ = null;
      if (originalRequestBuilder_ != null) {
        originalRequestBuilder_.dispose();
        originalRequestBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     */
    public otoroshi.next.plugins.grpc.ServerReflectionRequest.Builder getOriginalRequestBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getOriginalRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     */
    public otoroshi.next.plugins.grpc.ServerReflectionRequestOrBuilder getOriginalRequestOrBuilder() {
      if (originalRequestBuilder_ != null) {
        return originalRequestBuilder_.getMessageOrBuilder();
      } else {
        return originalRequest_ == null ?
            otoroshi.next.plugins.grpc.ServerReflectionRequest.getDefaultInstance() : originalRequest_;
      }
    }
    /**
     * <code>.grpc.reflection.v1alpha.ServerReflectionRequest original_request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ServerReflectionRequest, otoroshi.next.plugins.grpc.ServerReflectionRequest.Builder, otoroshi.next.plugins.grpc.ServerReflectionRequestOrBuilder> 
        getOriginalRequestFieldBuilder() {
      if (originalRequestBuilder_ == null) {
        originalRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            otoroshi.next.plugins.grpc.ServerReflectionRequest, otoroshi.next.plugins.grpc.ServerReflectionRequest.Builder, otoroshi.next.plugins.grpc.ServerReflectionRequestOrBuilder>(
                getOriginalRequest(),
                getParentForChildren(),
                isClean());
        originalRequest_ = null;
      }
      return originalRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.FileDescriptorResponse, otoroshi.next.plugins.grpc.FileDescriptorResponse.Builder, otoroshi.next.plugins.grpc.FileDescriptorResponseOrBuilder> fileDescriptorResponseBuilder_;
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     * @return Whether the fileDescriptorResponse field is set.
     */
    @java.lang.Override
    public boolean hasFileDescriptorResponse() {
      return messageResponseCase_ == 4;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     * @return The fileDescriptorResponse.
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.FileDescriptorResponse getFileDescriptorResponse() {
      if (fileDescriptorResponseBuilder_ == null) {
        if (messageResponseCase_ == 4) {
          return (otoroshi.next.plugins.grpc.FileDescriptorResponse) messageResponse_;
        }
        return otoroshi.next.plugins.grpc.FileDescriptorResponse.getDefaultInstance();
      } else {
        if (messageResponseCase_ == 4) {
          return fileDescriptorResponseBuilder_.getMessage();
        }
        return otoroshi.next.plugins.grpc.FileDescriptorResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public Builder setFileDescriptorResponse(otoroshi.next.plugins.grpc.FileDescriptorResponse value) {
      if (fileDescriptorResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageResponse_ = value;
        onChanged();
      } else {
        fileDescriptorResponseBuilder_.setMessage(value);
      }
      messageResponseCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public Builder setFileDescriptorResponse(
        otoroshi.next.plugins.grpc.FileDescriptorResponse.Builder builderForValue) {
      if (fileDescriptorResponseBuilder_ == null) {
        messageResponse_ = builderForValue.build();
        onChanged();
      } else {
        fileDescriptorResponseBuilder_.setMessage(builderForValue.build());
      }
      messageResponseCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public Builder mergeFileDescriptorResponse(otoroshi.next.plugins.grpc.FileDescriptorResponse value) {
      if (fileDescriptorResponseBuilder_ == null) {
        if (messageResponseCase_ == 4 &&
            messageResponse_ != otoroshi.next.plugins.grpc.FileDescriptorResponse.getDefaultInstance()) {
          messageResponse_ = otoroshi.next.plugins.grpc.FileDescriptorResponse.newBuilder((otoroshi.next.plugins.grpc.FileDescriptorResponse) messageResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          messageResponse_ = value;
        }
        onChanged();
      } else {
        if (messageResponseCase_ == 4) {
          fileDescriptorResponseBuilder_.mergeFrom(value);
        } else {
          fileDescriptorResponseBuilder_.setMessage(value);
        }
      }
      messageResponseCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public Builder clearFileDescriptorResponse() {
      if (fileDescriptorResponseBuilder_ == null) {
        if (messageResponseCase_ == 4) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
          onChanged();
        }
      } else {
        if (messageResponseCase_ == 4) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
        }
        fileDescriptorResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    public otoroshi.next.plugins.grpc.FileDescriptorResponse.Builder getFileDescriptorResponseBuilder() {
      return getFileDescriptorResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.FileDescriptorResponseOrBuilder getFileDescriptorResponseOrBuilder() {
      if ((messageResponseCase_ == 4) && (fileDescriptorResponseBuilder_ != null)) {
        return fileDescriptorResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageResponseCase_ == 4) {
          return (otoroshi.next.plugins.grpc.FileDescriptorResponse) messageResponse_;
        }
        return otoroshi.next.plugins.grpc.FileDescriptorResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer file_by_filename, file_containing_symbol,
     * file_containing_extension requests with transitive dependencies. As
     * the repeated label is not allowed in oneof fields, we use a
     * FileDescriptorResponse message to encapsulate the repeated fields.
     * The reflection service is allowed to avoid sending FileDescriptorProtos
     * that were previously sent in response to earlier requests in the stream.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.FileDescriptorResponse file_descriptor_response = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.FileDescriptorResponse, otoroshi.next.plugins.grpc.FileDescriptorResponse.Builder, otoroshi.next.plugins.grpc.FileDescriptorResponseOrBuilder> 
        getFileDescriptorResponseFieldBuilder() {
      if (fileDescriptorResponseBuilder_ == null) {
        if (!(messageResponseCase_ == 4)) {
          messageResponse_ = otoroshi.next.plugins.grpc.FileDescriptorResponse.getDefaultInstance();
        }
        fileDescriptorResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            otoroshi.next.plugins.grpc.FileDescriptorResponse, otoroshi.next.plugins.grpc.FileDescriptorResponse.Builder, otoroshi.next.plugins.grpc.FileDescriptorResponseOrBuilder>(
                (otoroshi.next.plugins.grpc.FileDescriptorResponse) messageResponse_,
                getParentForChildren(),
                isClean());
        messageResponse_ = null;
      }
      messageResponseCase_ = 4;
      onChanged();
      return fileDescriptorResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ExtensionNumberResponse, otoroshi.next.plugins.grpc.ExtensionNumberResponse.Builder, otoroshi.next.plugins.grpc.ExtensionNumberResponseOrBuilder> allExtensionNumbersResponseBuilder_;
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     * @return Whether the allExtensionNumbersResponse field is set.
     */
    @java.lang.Override
    public boolean hasAllExtensionNumbersResponse() {
      return messageResponseCase_ == 5;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     * @return The allExtensionNumbersResponse.
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.ExtensionNumberResponse getAllExtensionNumbersResponse() {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (messageResponseCase_ == 5) {
          return (otoroshi.next.plugins.grpc.ExtensionNumberResponse) messageResponse_;
        }
        return otoroshi.next.plugins.grpc.ExtensionNumberResponse.getDefaultInstance();
      } else {
        if (messageResponseCase_ == 5) {
          return allExtensionNumbersResponseBuilder_.getMessage();
        }
        return otoroshi.next.plugins.grpc.ExtensionNumberResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public Builder setAllExtensionNumbersResponse(otoroshi.next.plugins.grpc.ExtensionNumberResponse value) {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageResponse_ = value;
        onChanged();
      } else {
        allExtensionNumbersResponseBuilder_.setMessage(value);
      }
      messageResponseCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public Builder setAllExtensionNumbersResponse(
        otoroshi.next.plugins.grpc.ExtensionNumberResponse.Builder builderForValue) {
      if (allExtensionNumbersResponseBuilder_ == null) {
        messageResponse_ = builderForValue.build();
        onChanged();
      } else {
        allExtensionNumbersResponseBuilder_.setMessage(builderForValue.build());
      }
      messageResponseCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public Builder mergeAllExtensionNumbersResponse(otoroshi.next.plugins.grpc.ExtensionNumberResponse value) {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (messageResponseCase_ == 5 &&
            messageResponse_ != otoroshi.next.plugins.grpc.ExtensionNumberResponse.getDefaultInstance()) {
          messageResponse_ = otoroshi.next.plugins.grpc.ExtensionNumberResponse.newBuilder((otoroshi.next.plugins.grpc.ExtensionNumberResponse) messageResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          messageResponse_ = value;
        }
        onChanged();
      } else {
        if (messageResponseCase_ == 5) {
          allExtensionNumbersResponseBuilder_.mergeFrom(value);
        } else {
          allExtensionNumbersResponseBuilder_.setMessage(value);
        }
      }
      messageResponseCase_ = 5;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public Builder clearAllExtensionNumbersResponse() {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (messageResponseCase_ == 5) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
          onChanged();
        }
      } else {
        if (messageResponseCase_ == 5) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
        }
        allExtensionNumbersResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    public otoroshi.next.plugins.grpc.ExtensionNumberResponse.Builder getAllExtensionNumbersResponseBuilder() {
      return getAllExtensionNumbersResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.ExtensionNumberResponseOrBuilder getAllExtensionNumbersResponseOrBuilder() {
      if ((messageResponseCase_ == 5) && (allExtensionNumbersResponseBuilder_ != null)) {
        return allExtensionNumbersResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageResponseCase_ == 5) {
          return (otoroshi.next.plugins.grpc.ExtensionNumberResponse) messageResponse_;
        }
        return otoroshi.next.plugins.grpc.ExtensionNumberResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer all_extension_numbers_of_type requst.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ExtensionNumberResponse all_extension_numbers_response = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ExtensionNumberResponse, otoroshi.next.plugins.grpc.ExtensionNumberResponse.Builder, otoroshi.next.plugins.grpc.ExtensionNumberResponseOrBuilder> 
        getAllExtensionNumbersResponseFieldBuilder() {
      if (allExtensionNumbersResponseBuilder_ == null) {
        if (!(messageResponseCase_ == 5)) {
          messageResponse_ = otoroshi.next.plugins.grpc.ExtensionNumberResponse.getDefaultInstance();
        }
        allExtensionNumbersResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            otoroshi.next.plugins.grpc.ExtensionNumberResponse, otoroshi.next.plugins.grpc.ExtensionNumberResponse.Builder, otoroshi.next.plugins.grpc.ExtensionNumberResponseOrBuilder>(
                (otoroshi.next.plugins.grpc.ExtensionNumberResponse) messageResponse_,
                getParentForChildren(),
                isClean());
        messageResponse_ = null;
      }
      messageResponseCase_ = 5;
      onChanged();
      return allExtensionNumbersResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ListServiceResponse, otoroshi.next.plugins.grpc.ListServiceResponse.Builder, otoroshi.next.plugins.grpc.ListServiceResponseOrBuilder> listServicesResponseBuilder_;
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     * @return Whether the listServicesResponse field is set.
     */
    @java.lang.Override
    public boolean hasListServicesResponse() {
      return messageResponseCase_ == 6;
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     * @return The listServicesResponse.
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.ListServiceResponse getListServicesResponse() {
      if (listServicesResponseBuilder_ == null) {
        if (messageResponseCase_ == 6) {
          return (otoroshi.next.plugins.grpc.ListServiceResponse) messageResponse_;
        }
        return otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance();
      } else {
        if (messageResponseCase_ == 6) {
          return listServicesResponseBuilder_.getMessage();
        }
        return otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     */
    public Builder setListServicesResponse(otoroshi.next.plugins.grpc.ListServiceResponse value) {
      if (listServicesResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageResponse_ = value;
        onChanged();
      } else {
        listServicesResponseBuilder_.setMessage(value);
      }
      messageResponseCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     */
    public Builder setListServicesResponse(
        otoroshi.next.plugins.grpc.ListServiceResponse.Builder builderForValue) {
      if (listServicesResponseBuilder_ == null) {
        messageResponse_ = builderForValue.build();
        onChanged();
      } else {
        listServicesResponseBuilder_.setMessage(builderForValue.build());
      }
      messageResponseCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     */
    public Builder mergeListServicesResponse(otoroshi.next.plugins.grpc.ListServiceResponse value) {
      if (listServicesResponseBuilder_ == null) {
        if (messageResponseCase_ == 6 &&
            messageResponse_ != otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance()) {
          messageResponse_ = otoroshi.next.plugins.grpc.ListServiceResponse.newBuilder((otoroshi.next.plugins.grpc.ListServiceResponse) messageResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          messageResponse_ = value;
        }
        onChanged();
      } else {
        if (messageResponseCase_ == 6) {
          listServicesResponseBuilder_.mergeFrom(value);
        } else {
          listServicesResponseBuilder_.setMessage(value);
        }
      }
      messageResponseCase_ = 6;
      return this;
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     */
    public Builder clearListServicesResponse() {
      if (listServicesResponseBuilder_ == null) {
        if (messageResponseCase_ == 6) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
          onChanged();
        }
      } else {
        if (messageResponseCase_ == 6) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
        }
        listServicesResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     */
    public otoroshi.next.plugins.grpc.ListServiceResponse.Builder getListServicesResponseBuilder() {
      return getListServicesResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.ListServiceResponseOrBuilder getListServicesResponseOrBuilder() {
      if ((messageResponseCase_ == 6) && (listServicesResponseBuilder_ != null)) {
        return listServicesResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageResponseCase_ == 6) {
          return (otoroshi.next.plugins.grpc.ListServiceResponse) messageResponse_;
        }
        return otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used to answer list_services request.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ListServiceResponse list_services_response = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ListServiceResponse, otoroshi.next.plugins.grpc.ListServiceResponse.Builder, otoroshi.next.plugins.grpc.ListServiceResponseOrBuilder> 
        getListServicesResponseFieldBuilder() {
      if (listServicesResponseBuilder_ == null) {
        if (!(messageResponseCase_ == 6)) {
          messageResponse_ = otoroshi.next.plugins.grpc.ListServiceResponse.getDefaultInstance();
        }
        listServicesResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            otoroshi.next.plugins.grpc.ListServiceResponse, otoroshi.next.plugins.grpc.ListServiceResponse.Builder, otoroshi.next.plugins.grpc.ListServiceResponseOrBuilder>(
                (otoroshi.next.plugins.grpc.ListServiceResponse) messageResponse_,
                getParentForChildren(),
                isClean());
        messageResponse_ = null;
      }
      messageResponseCase_ = 6;
      onChanged();
      return listServicesResponseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ErrorResponse, otoroshi.next.plugins.grpc.ErrorResponse.Builder, otoroshi.next.plugins.grpc.ErrorResponseOrBuilder> errorResponseBuilder_;
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     * @return Whether the errorResponse field is set.
     */
    @java.lang.Override
    public boolean hasErrorResponse() {
      return messageResponseCase_ == 7;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     * @return The errorResponse.
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.ErrorResponse getErrorResponse() {
      if (errorResponseBuilder_ == null) {
        if (messageResponseCase_ == 7) {
          return (otoroshi.next.plugins.grpc.ErrorResponse) messageResponse_;
        }
        return otoroshi.next.plugins.grpc.ErrorResponse.getDefaultInstance();
      } else {
        if (messageResponseCase_ == 7) {
          return errorResponseBuilder_.getMessage();
        }
        return otoroshi.next.plugins.grpc.ErrorResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     */
    public Builder setErrorResponse(otoroshi.next.plugins.grpc.ErrorResponse value) {
      if (errorResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageResponse_ = value;
        onChanged();
      } else {
        errorResponseBuilder_.setMessage(value);
      }
      messageResponseCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     */
    public Builder setErrorResponse(
        otoroshi.next.plugins.grpc.ErrorResponse.Builder builderForValue) {
      if (errorResponseBuilder_ == null) {
        messageResponse_ = builderForValue.build();
        onChanged();
      } else {
        errorResponseBuilder_.setMessage(builderForValue.build());
      }
      messageResponseCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     */
    public Builder mergeErrorResponse(otoroshi.next.plugins.grpc.ErrorResponse value) {
      if (errorResponseBuilder_ == null) {
        if (messageResponseCase_ == 7 &&
            messageResponse_ != otoroshi.next.plugins.grpc.ErrorResponse.getDefaultInstance()) {
          messageResponse_ = otoroshi.next.plugins.grpc.ErrorResponse.newBuilder((otoroshi.next.plugins.grpc.ErrorResponse) messageResponse_)
              .mergeFrom(value).buildPartial();
        } else {
          messageResponse_ = value;
        }
        onChanged();
      } else {
        if (messageResponseCase_ == 7) {
          errorResponseBuilder_.mergeFrom(value);
        } else {
          errorResponseBuilder_.setMessage(value);
        }
      }
      messageResponseCase_ = 7;
      return this;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     */
    public Builder clearErrorResponse() {
      if (errorResponseBuilder_ == null) {
        if (messageResponseCase_ == 7) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
          onChanged();
        }
      } else {
        if (messageResponseCase_ == 7) {
          messageResponseCase_ = 0;
          messageResponse_ = null;
        }
        errorResponseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     */
    public otoroshi.next.plugins.grpc.ErrorResponse.Builder getErrorResponseBuilder() {
      return getErrorResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     */
    @java.lang.Override
    public otoroshi.next.plugins.grpc.ErrorResponseOrBuilder getErrorResponseOrBuilder() {
      if ((messageResponseCase_ == 7) && (errorResponseBuilder_ != null)) {
        return errorResponseBuilder_.getMessageOrBuilder();
      } else {
        if (messageResponseCase_ == 7) {
          return (otoroshi.next.plugins.grpc.ErrorResponse) messageResponse_;
        }
        return otoroshi.next.plugins.grpc.ErrorResponse.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * This message is used when an error occurs.
     * </pre>
     *
     * <code>.grpc.reflection.v1alpha.ErrorResponse error_response = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        otoroshi.next.plugins.grpc.ErrorResponse, otoroshi.next.plugins.grpc.ErrorResponse.Builder, otoroshi.next.plugins.grpc.ErrorResponseOrBuilder> 
        getErrorResponseFieldBuilder() {
      if (errorResponseBuilder_ == null) {
        if (!(messageResponseCase_ == 7)) {
          messageResponse_ = otoroshi.next.plugins.grpc.ErrorResponse.getDefaultInstance();
        }
        errorResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            otoroshi.next.plugins.grpc.ErrorResponse, otoroshi.next.plugins.grpc.ErrorResponse.Builder, otoroshi.next.plugins.grpc.ErrorResponseOrBuilder>(
                (otoroshi.next.plugins.grpc.ErrorResponse) messageResponse_,
                getParentForChildren(),
                isClean());
        messageResponse_ = null;
      }
      messageResponseCase_ = 7;
      onChanged();
      return errorResponseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.reflection.v1alpha.ServerReflectionResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.reflection.v1alpha.ServerReflectionResponse)
  private static final otoroshi.next.plugins.grpc.ServerReflectionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new otoroshi.next.plugins.grpc.ServerReflectionResponse();
  }

  public static otoroshi.next.plugins.grpc.ServerReflectionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerReflectionResponse>
      PARSER = new com.google.protobuf.AbstractParser<ServerReflectionResponse>() {
    @java.lang.Override
    public ServerReflectionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ServerReflectionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerReflectionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public otoroshi.next.plugins.grpc.ServerReflectionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

