{{- if not .Values.env.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "otoroshi.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ template "otoroshi.chart" . }}
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    meta.helm.sh/release-name: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ .Values.env.password | quote }}
  clientId: {{ .Values.env.clientId | quote }}
  clientSecret: {{ .Values.env.clientSecret | quote }}
  otoroshiSecret: {{ .Values.env.secret | quote }}
{{- end }}
