{{- if not .Values.env.existingSecret }}
{{- $creds := include "otoroshi.adminCredentials" . | fromJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otoroshi.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ $creds.password | quote }}
  clientId: {{ $creds.clientId | quote }}
  clientSecret: {{ $creds.clientSecret | quote }}
  otoroshiSecret: {{ $creds.otoroshiSecret | quote }}
{{- end }}
