apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otoroshi-admin-user
rules:
  # Core resources (existing Otoroshi needs)
  - apiGroups: [""]
    resources: [services, endpoints, secrets, configmaps, namespaces, pods]
    verbs: [get, list, watch]
  - apiGroups: ["apps"]
    resources: [deployments]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [secrets, configmaps]
    verbs: [update, create, delete]
  # Ingress
  - apiGroups: [extensions, networking.k8s.io]
    resources: [ingresses, ingressclasses]
    verbs: [get, list, watch]
  - apiGroups: [extensions, networking.k8s.io]
    resources: [ingresses/status]
    verbs: [update]
  # Otoroshi CRDs
  - apiGroups: [proxy.otoroshi.io]
    resources: ["*"]
    verbs: [get, list, watch]
  # Gateway API — read resources
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses, gateways, httproutes, grpcroutes, referencegrants]
    verbs: [get, list, watch]
  # Gateway API — update status subresources
  - apiGroups: [gateway.networking.k8s.io]
    resources: [gatewayclasses/status, gateways/status, httproutes/status, grpcroutes/status]
    verbs: [get, update, patch]