apiVersion: v2
name: otoroshi
description: An Otoroshi based Kubernetes ingress controller
type: application
version: 17.16.0-dev
appVersion: 17.16.0-dev
kubeVersion: ">=1.25.0-0"
keywords:
  - otoroshi
  - ingress
  - gateway
  - apim
  - reverseproxy
  - apimanager
sources:
  - https://github.com/MAIF/otoroshi
maintainers:
  - name: mathieuancelin
icon: https://raw.githubusercontent.com/MAIF/otoroshi/master/resources/otoroshi-logo.png
dependencies:
  - name: redis
    version: 0.29.2
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.deploy
